# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Process(models.Model):
    order_id = models.CharField(max_length=30, blank=True, null=True, db_comment='订单编号')
    customer = models.CharField(max_length=30, blank=True, null=True, db_comment='客户')
    test_item = models.CharField(max_length=50, blank=True, null=True, db_comment='检测项目')
    lot_wafer_sample_id = models.CharField(max_length=255, blank=True, null=True, db_comment='Lot/Wafer/Sample ID')
    status = models.CharField(db_column='STATUS', max_length=20, blank=True, null=True, db_comment='状态')  # Field name made lowercase.
    testing_engineer = models.CharField(max_length=20, blank=True, null=True, db_comment='检测工程师')
    testing_machine = models.CharField(max_length=30, blank=True, null=True, db_comment='检测机台')
    machine_model = models.CharField(max_length=50, blank=True, null=True, db_comment='检测机台详细型号')
    machine_code = models.CharField(max_length=30, blank=True, null=True, db_comment='检测机台工序设备编码')
    machine_unit = models.CharField(max_length=20, blank=True, null=True, db_comment='检测机台单位')
    sample_receive_time = models.DateTimeField(blank=True, null=True, db_comment='样点接收时间')
    sample_validity_hours = models.IntegerField(blank=True, null=True, db_comment='样点时效（小时）')
    urgency_level = models.CharField(max_length=20, blank=True, null=True, db_comment='加急程度')
    is_outsource = models.CharField(max_length=10, blank=True, null=True, db_comment='是否委外')
    start_time = models.DateTimeField(blank=True, null=True, db_comment='开始时间')
    end_time = models.DateTimeField(blank=True, null=True, db_comment='结束时间')
    process_category = models.CharField(max_length=255, blank=True, null=True, db_comment='工序类别')
    is_upload_result = models.CharField(max_length=10, blank=True, null=True, db_comment='是否上传结果')
    sample_id = models.CharField(max_length=30, blank=True, null=True, db_comment='检测样点')
    equivalent_point_quantity = models.IntegerField(blank=True, null=True, db_comment='等效点数量')
    execution_plan = models.CharField(max_length=255, blank=True, null=True, db_comment='执行方案')
    associated_machine = models.CharField(max_length=50, blank=True, null=True, db_comment='关联机台（隐藏）')
    priority_level = models.IntegerField(blank=True, null=True, db_comment='优先级')
    time_consumption_minutes = models.IntegerField(blank=True, null=True, db_comment='耗时（分钟）')
    original_test_task = models.CharField(max_length=50, blank=True, null=True, db_comment='原检测任务')
    machine_reconciliation_note = models.CharField(max_length=255, blank=True, null=True, db_comment='机台对账单')
    review_comment = models.CharField(max_length=50, blank=True, null=True, db_comment='审核备注')
    is_canceled = models.CharField(max_length=10, blank=True, null=True, db_comment='是否取消')
    outsourcing_result_file = models.CharField(max_length=255, blank=True, null=True, db_comment='委外结果文件')
    process_id = models.CharField(primary_key=True, max_length=30, db_comment='工序编号')
    customer_sample_id = models.CharField(max_length=255, blank=True, null=True, db_comment='客户样点编号')
    last_process_step = models.CharField(max_length=50, blank=True, null=True, db_comment='最后工艺步骤')
    main_attention_info = models.CharField(max_length=255, blank=True, null=True, db_comment='主要关注信息')
    slice_position = models.CharField(max_length=255, blank=True, null=True, db_comment='切片位置')
    sample_preparation_direction = models.CharField(max_length=30, blank=True, null=True, db_comment='制样方向')
    notes = models.CharField(max_length=255, blank=True, null=True, db_comment='注意事项')
    process_note = models.CharField(max_length=255, blank=True, null=True, db_comment='工序备注')
    supplier_service_item = models.CharField(max_length=50, blank=True, null=True, db_comment='供应商服务项目')
    process_related_result = models.CharField(max_length=50, blank=True, null=True, db_comment='工序相关结果')
    engineer_reconciliation_note = models.CharField(max_length=255, blank=True, null=True, db_comment='工程师对账单')
    engineer_reconciliation_status = models.CharField(max_length=20, blank=True, null=True, db_comment='工程师对账状态')
    associated_machine_reconciliation_detail = models.CharField(max_length=255, blank=True, null=True, db_comment='关联机台对账明细')
    machine_reconciliation_status = models.CharField(max_length=20, blank=True, null=True, db_comment='机台对账状态')
    base_material = models.CharField(max_length=30, blank=True, null=True, db_comment='基底材料')
    e_beam = models.CharField(max_length=30, blank=True, null=True, db_comment='E - beam')
    sample_materials = models.CharField(max_length=50, blank=True, null=True, db_comment='样品所含材质')
    sample_confirmation_date = models.DateTimeField(blank=True, null=True, db_comment='样点确认日期')
    sample_confirmation_time = models.DateTimeField(blank=True, null=True, db_comment='样点确认时间')
    order_date = models.DateTimeField(blank=True, null=True, db_comment='订单日期')
    is_calculate_performance = models.CharField(max_length=10, blank=True, null=True, db_comment='是否计算绩效')
    billing_quantity = models.FloatField(blank=True, null=True, db_comment='计费数量')
    create_time = models.DateTimeField(blank=True, null=True, db_comment='创建时间')
    modify_time = models.DateTimeField(blank=True, null=True, db_comment='修改时间')
    failure_proof = models.CharField(max_length=50, blank=True, null=True, db_comment='失败证明')
    order_category = models.CharField(max_length=20, blank=True, null=True, db_comment='订单类目')
    supplier = models.CharField(max_length=30, blank=True, null=True, db_comment='供应商')
    charge_quantity = models.FloatField(blank=True, null=True, db_comment='收费数量')
    engineer_region = models.CharField(max_length=30, blank=True, null=True, db_comment='工程师区域')
    standard_working_hours_minutes = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='标准工时（分钟）')
    is_rework_process = models.CharField(max_length=10, blank=True, null=True, db_comment='是否为返工工序')
    experience_summary = models.CharField(max_length=50, blank=True, null=True, db_comment='经验总结')
    urgency_coefficient = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='加急系数')
    sample_receive_date = models.DateTimeField(blank=True, null=True, db_comment='样点接收日期')
    associated_customer = models.CharField(max_length=30, blank=True, null=True, db_comment='关联客户')
    associated_transfer_record = models.CharField(max_length=50, blank=True, null=True, db_comment='关联转交记录')
    closing_date = models.DateTimeField(blank=True, null=True, db_comment='结案日期')
    machine_supplier = models.CharField(max_length=30, blank=True, null=True, db_comment='机台供应商')
    scan_to_machine_reminder_minutes = models.CharField(max_length=30, blank=True, null=True, db_comment='分钟内扫码上机提醒')
    test_item_name = models.CharField(max_length=30, blank=True, null=True, db_comment='检测项目名')
    supplier_reconciliation_status = models.CharField(max_length=30, blank=True, null=True, db_comment='供应商对账状态')
    supplier_reconciliation_detail = models.CharField(max_length=50, blank=True, null=True, db_comment='供应商对账单明细')
    supplier_reconciliation_note = models.CharField(max_length=50, blank=True, null=True, db_comment='供应商对账单')
    supplier_charge_quantity = models.FloatField(blank=True, null=True, db_comment='供应商收费数量')
    received_customer_quantity = models.FloatField(blank=True, null=True, db_comment='实收客户数量')
    validity_start_time = models.DateTimeField(blank=True, null=True, db_comment='时效起算时间')
    validity = models.CharField(max_length=20, blank=True, null=True, db_comment='时效')
    process_start_date = models.DateTimeField(blank=True, null=True, db_comment='工序开始日期')
    direct_labor_cost = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='直接人工成本')
    management_labor_cost = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='管理人工成本')
    total_labor_cost = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='总人工成本')
    equipment_maintenance_cost = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='设备维护费')
    equipment_depreciation = models.CharField(max_length=50, blank=True, null=True, db_comment='设备折旧')
    laboratory_equipment_consumables = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='实验室设备易耗品')
    intangible_asset_amortization = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='无形资产摊销')
    office_expense = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='办公费')
    entertainment_expense = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='业务招待费')
    transportation_expense = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='市内交通费')
    car_expense = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='汽车费用')
    travel_expense = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='差旅费')
    rent_and_utility_expense = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='租金水电')
    freight_expense = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='货运费')
    express_expense = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='快递费')
    business_expense = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='商务费用')
    supplier_cost = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='供应商成本')
    sim_salary = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='SIMS 薪酬')
    outsourcing_salary = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='委外薪酬')
    external_aid_cost = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='外援成本')
    total_cost = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='总成本')
    supplier_service_item_quote_untaxed = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='供应商服务项目报价(未税)')
    supplier_service_item_quote_taxed = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='供应商服务项目报价(含税)')
    supplier_cost_again = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='供应商成本')
    customer_full_name1 = models.CharField(max_length=50, blank=True, null=True, db_comment='客户全称1')
    sim_outsourcing_test_cost = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='SIMS委外检测成本')
    performance_working_hours = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='绩效工时')
    note = models.CharField(max_length=255, blank=True, null=True, db_comment='备注')
    working_hours = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='工时')
    associated_report_detail = models.CharField(max_length=255, blank=True, null=True, db_comment='关联研发报表明细')
    sender_name = models.CharField(max_length=50, blank=True, null=True, db_comment='送件人名称')
    demo_urgency = models.IntegerField(blank=True, null=True, db_comment='demo/加急')
    test_item_name_virtual = models.CharField(max_length=50, blank=True, null=True, db_comment='检测项目名(虚拟)')

    class Meta:
        managed = False
        db_table = 'process'
        db_table_comment = '工序列表'


class MachineUsageRecord(models.Model):
    record_id = models.AutoField(primary_key=True, db_comment='记录编号')
    machine_name = models.CharField(max_length=50, blank=True, null=True, db_comment='机台')
    usage_type = models.CharField(max_length=30, blank=True, null=True, db_comment='使用类型')
    start_time = models.DateTimeField(blank=True, null=True, db_comment='开始时间')
    duration_minutes = models.IntegerField(blank=True, null=True, db_comment='耗时(min)')
    end_time = models.DateTimeField(blank=True, null=True, db_comment='结束时间')
    creator_name = models.CharField(max_length=20, blank=True, null=True, db_comment='创建人')
    creation_time = models.DateTimeField(blank=True, null=True, db_comment='创建时间')
    device_code = models.CharField(max_length=20, blank=True, null=True, db_comment='设备编码')
    shift = models.CharField(max_length=20, blank=True, null=True, db_comment='班次')

    class Meta:
        managed = False
        db_table = 'machine_usage_record'
        db_table_comment = '机台耗时记录表'


class Machine(models.Model):
    process_equipment_code = models.CharField(primary_key=True, max_length=50, db_comment='工序设备编码')
    city = models.CharField(max_length=30, blank=True, null=True, db_comment='城市')
    category = models.CharField(max_length=30, blank=True, null=True, db_comment='类别')
    sub_category = models.CharField(max_length=50, blank=True, null=True, db_comment='子类')
    unit = models.CharField(max_length=50, blank=True, null=True, db_comment='单位')
    supplier = models.CharField(max_length=100, blank=True, null=True, db_comment='所属供应商')
    detailed_model = models.CharField(max_length=100, blank=True, null=True, db_comment='详细型号')
    serial_number = models.CharField(max_length=50, blank=True, null=True, db_comment='序列号')
    internal_external_distinction = models.CharField(max_length=20, blank=True, null=True, db_comment='内外部区分')
    machine_configuration = models.CharField(max_length=200, blank=True, null=True, db_comment='机台配置')
    price = models.CharField(max_length=30, blank=True, null=True, db_comment='价格')
    preset_price_before_tax = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='机台预设价格(￥/分钟)(未税)')
    current_user = models.CharField(max_length=50, blank=True, null=True, db_comment='正在使用人员')
    project_start_time = models.DateTimeField(blank=True, null=True, db_comment='项目开始时间')
    usage_status = models.CharField(max_length=100, blank=True, null=True, db_comment='使用情况')
    remark = models.CharField(max_length=100, blank=True, null=True, db_comment='备注')
    preset_price_after_tax = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='机台预设价格(￥/分钟)(含税)')
    tax_rate = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, db_comment='税率')

    class Meta:
        managed = False
        db_table = 'machine'
        db_table_comment = '机台列表相关信息表'


class Order(models.Model):
    order_id = models.CharField(primary_key=True, max_length=30, db_comment='订单编号')
    customer = models.CharField(max_length=30, blank=True, null=True, db_comment='客户')
    priority = models.CharField(max_length=10, blank=True, null=True, db_comment='优先级')
    order_status = models.CharField(max_length=20, blank=True, null=True, db_comment='订单状态')
    sample_status = models.CharField(max_length=20, blank=True, null=True, db_comment='样品状态')
    process_status = models.CharField(max_length=20, blank=True, null=True, db_comment='工序状态')
    order_category = models.CharField(max_length=20, blank=True, null=True, db_comment='订单类目')
    sample_quantity = models.IntegerField(blank=True, null=True, db_comment='样点数量')
    sender_name = models.CharField(max_length=20, blank=True, null=True, db_comment='寄件人名称')
    sender_phone = models.CharField(max_length=50, blank=True, null=True, db_comment='寄件人电话')
    sample_receiver = models.CharField(max_length=20, blank=True, null=True, db_comment='样点接收人员')
    sample_receipt_image = models.CharField(max_length=255, blank=True, null=True, db_comment='样点接受留图（弃用）')
    order_salesman = models.CharField(max_length=20, blank=True, null=True, db_comment='订单销售')
    sales_contact = models.CharField(max_length=20, blank=True, null=True, db_comment='销售联系方式')
    is_outsource = models.CharField(max_length=10, blank=True, null=True, db_comment='是否委外')
    order_type = models.CharField(max_length=20, blank=True, null=True, db_comment='订单类型')
    customer_id = models.CharField(max_length=20, blank=True, null=True, db_comment='客户编号')
    demo_case = models.CharField(max_length=20, blank=True, null=True, db_comment='demo案件')
    receive_time = models.DateTimeField(blank=True, null=True, db_comment='接收时间')
    requirement_confirm_time = models.DateTimeField(blank=True, null=True, db_comment='需求确认时间')
    validity_start_time = models.DateTimeField(blank=True, null=True, db_comment='时效起算时间')
    closing_date = models.DateTimeField(blank=True, null=True, db_comment='结案日期')
    customer_reconciliation_date = models.DateTimeField(blank=True, null=True, db_comment='客户对账日期')
    invoice_date = models.DateTimeField(blank=True, null=True, db_comment='开票日期')
    handlebook_attachment = models.CharField(max_length=255, blank=True, null=True, db_comment='Handlebook附件')
    review_department = models.CharField(max_length=20, blank=True, null=True, db_comment='审核部门')
    reviewer = models.CharField(max_length=20, blank=True, null=True, db_comment='审核人')
    review_time = models.DateTimeField(blank=True, null=True, db_comment='审核时间')
    review_reason = models.CharField(max_length=255, blank=True, null=True, db_comment='审核原因')
    outsourcing_supplier = models.CharField(max_length=20, blank=True, null=True, db_comment='外包供应商')
    upload_result = models.CharField(max_length=255, blank=True, null=True, db_comment='上传结果')
    customer_order_number = models.CharField(max_length=255, blank=True, null=True, db_comment='客户单号')
    closing_time = models.TimeField(blank=True, null=True, db_comment='结案时间')
    customer_requirement = models.TextField(blank=True, null=True, db_comment='客户需求')
    closer = models.CharField(max_length=50, blank=True, null=True, db_comment='结案人')
    commission_to_report_validity = models.CharField(max_length=20, blank=True, null=True, db_comment='委案到报告时效')
    sample_to_report_validity = models.CharField(max_length=20, blank=True, null=True, db_comment='收样到报告时效')
    case_analysis_project_type = models.CharField(max_length=255, blank=True, null=True, db_comment='案例分析项目类型')
    validity_requirement_hours = models.FloatField(blank=True, null=True, db_comment='时效要求(h)')
    customer_bill_status = models.CharField(max_length=20, blank=True, null=True, db_comment='客户账单状态')
    engineer_bill_status = models.CharField(max_length=20, blank=True, null=True, db_comment='工程师账单状态')
    machine_bill_status = models.CharField(max_length=20, blank=True, null=True, db_comment='机台账单状态')
    order_amount = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='订单金额')
    review_date = models.DateTimeField(blank=True, null=True, db_comment='审核日期')
    create_time = models.DateTimeField(db_comment='创建时间')
    modify_time = models.DateTimeField(db_comment='修改时间')
    sender = models.CharField(max_length=20, blank=True, null=True, db_comment='寄件人')
    sender_email = models.CharField(max_length=50, blank=True, null=True, db_comment='寄件人邮箱')
    requirement_confirm_date = models.DateTimeField(blank=True, null=True, db_comment='需求确认日期')
    test_item = models.CharField(max_length=20, blank=True, null=True, db_comment='检测项')
    is_report_required = models.CharField(max_length=10, blank=True, null=True, db_comment='是否需要报告')
    report_format = models.CharField(max_length=20, blank=True, null=True, db_comment='报告形式')
    sample_processing_method = models.CharField(max_length=20, blank=True, null=True, db_comment='样品处理方法')
    execution_place = models.CharField(max_length=20, blank=True, null=True, db_comment='执行地')
    is_order_successful = models.CharField(max_length=10, blank=True, null=True, db_comment='订单是否一次性成功')
    specimen_quantity = models.IntegerField(blank=True, null=True, db_comment='样品数量')

    class Meta:
        managed = False
        db_table = 'order'


class Sample(models.Model):
    order_id = models.CharField(max_length=30, blank=True, null=True, db_comment='关联订单')
    customer_sample_id = models.CharField(max_length=255, blank=True, null=True, db_comment='客户样点编号')
    customer_name = models.CharField(max_length=30, blank=True, null=True, db_comment='客户名')
    test_project = models.CharField(max_length=255, blank=True, null=True, db_comment='检测项目')
    receive_time = models.DateTimeField(blank=True, null=True)
    sender = models.CharField(max_length=50, blank=True, null=True, db_comment='送件人')
    status = models.CharField(db_column='STATUS', max_length=20, blank=True, null=True, db_comment='状态')  # Field name made lowercase.
    slice_position = models.CharField(max_length=255, blank=True, null=True, db_comment='切片位置')
    case_analysis_project_type = models.CharField(max_length=30, blank=True, null=True, db_comment='案件分析项目类型')
    process_status = models.CharField(max_length=20, blank=True, null=True, db_comment='工序状态')
    sample_quantity = models.IntegerField(blank=True, null=True, db_comment='样品数量')
    sample_validity_hours = models.IntegerField(blank=True, null=True, db_comment='样点时效(h)')
    last_process_step = models.CharField(max_length=50, blank=True, null=True, db_comment='最后工艺步骤')
    sample_preparation_direction = models.CharField(max_length=50, blank=True, null=True, db_comment='制样方向')
    task_assignee = models.CharField(max_length=20, blank=True, null=True, db_comment='任务分配人')
    notes = models.CharField(max_length=255, blank=True, null=True, db_comment='注意事项')
    main_attention_info = models.CharField(max_length=255, blank=True, null=True, db_comment='主要关注信息')
    reviewer = models.CharField(max_length=20, blank=True, null=True, db_comment='审核人')
    test_start_time = models.DateTimeField(blank=True, null=True, db_comment='检测开始时间')
    test_completion_time = models.DateTimeField(blank=True, null=True, db_comment='检测完成时间')
    task_assignment_time = models.DateTimeField(blank=True, null=True, db_comment='任务分配时间')
    expected_time_minutes = models.IntegerField(blank=True, null=True, db_comment='期望用时（分钟）')
    expected_completion_time = models.DateTimeField(blank=True, null=True, db_comment='期望完成时间')
    order_status = models.CharField(max_length=20, blank=True, null=True, db_comment='订单状态')
    sample_box_location = models.CharField(max_length=20, blank=True, null=True, db_comment='存放样点盒')
    execution_plan_file = models.CharField(max_length=50, blank=True, null=True, db_comment='执行方案（文件）')
    sample_id = models.CharField(primary_key=True, max_length=30, db_comment='样点编号')
    execution_plan = models.CharField(max_length=50, blank=True, null=True, db_comment='执行方案')
    base_material = models.CharField(max_length=50, blank=True, null=True, db_comment='基底材料')
    e_beam = models.CharField(max_length=50, blank=True, null=True, db_comment='E - beam')
    sample_materials = models.CharField(max_length=50, blank=True, null=True, db_comment='样品所含材质')
    sample_confirmation_date = models.DateTimeField(blank=True, null=True, db_comment='样点确认日期')
    sample_confirmation_time = models.CharField(max_length=30, blank=True, null=True, db_comment='样点确认时间')
    order_status_duplicated = models.CharField(max_length=20, blank=True, null=True, db_comment='订单状态')
    packaging_form = models.CharField(max_length=20, blank=True, null=True, db_comment='封装形式')
    project_category = models.CharField(max_length=20, blank=True, null=True, db_comment='项目分类')
    related_customer = models.CharField(max_length=30, blank=True, null=True, db_comment='关联客户')
    validity_start_date = models.DateTimeField(blank=True, null=True, db_comment='时效起算日期')
    validity_start_time = models.TimeField(blank=True, null=True, db_comment='时效起算时间')
    sample_holder = models.CharField(max_length=20, blank=True, null=True, db_comment='样点持有人')
    delivery_date = models.DateTimeField(blank=True, null=True, db_comment='交期日期')
    delivery_time = models.TimeField(blank=True, null=True, db_comment='交期时间')
    lot_wafer_sample_id = models.CharField(max_length=255, blank=True, null=True, db_comment='Lot/Wafer/Sample ID')
    process_audit_status = models.CharField(max_length=20, blank=True, null=True, db_comment='工序审核状态')

    class Meta:
        managed = False
        db_table = 'sample'
        db_table_comment = '样点列表'
