from django.db import models

class Order(models.Model):
    order_id = models.CharField(primary_key=True, max_length=30, db_comment='订单编号')
    customer = models.CharField(max_length=30, blank=True, null=True, db_comment='客户')
    priority = models.CharField(max_length=10, blank=True, null=True, db_comment='优先级')
    order_status = models.CharField(max_length=20, blank=True, null=True, db_comment='订单状态')
    sample_status = models.CharField(max_length=20, blank=True, null=True, db_comment='样品状态')
    process_status = models.CharField(max_length=20, blank=True, null=True, db_comment='工序状态')
    order_category = models.CharField(max_length=20, blank=True, null=True, db_comment='订单类目')
    sample_quantity = models.IntegerField(blank=True, null=True, db_comment='样点数量')
    sender_name = models.CharField(max_length=20, blank=True, null=True, db_comment='寄件人名称')
    sender_phone = models.CharField(max_length=20, blank=True, null=True, db_comment='寄件人电话')
    sample_receiver = models.CharField(max_length=20, blank=True, null=True, db_comment='样点接收人员')
    sample_receipt_image = models.CharField(max_length=255, blank=True, null=True, db_comment='样点接受留图（弃用）')
    order_salesman = models.CharField(max_length=20, blank=True, null=True, db_comment='订单销售')
    sales_contact = models.CharField(max_length=20, blank=True, null=True, db_comment='销售联系方式')
    is_outsource = models.CharField(max_length=10, blank=True, null=True, db_comment='是否委外')
    order_type = models.CharField(max_length=20, blank=True, null=True, db_comment='订单类型')
    customer_id = models.CharField(max_length=20, blank=True, null=True, db_comment='客户编号')
    demo_case = models.CharField(max_length=20, blank=True, null=True, db_comment='demo案件')
    receive_time = models.DateTimeField(blank=True, null=True, db_comment='接收时间')
    requirement_confirm_time = models.DateTimeField(blank=True, null=True, db_comment='需求确认时间')
    validity_start_time = models.DateTimeField(blank=True, null=True, db_comment='时效起算时间')
    closing_date = models.DateTimeField(blank=True, null=True, db_comment='结案日期')
    customer_reconciliation_date = models.DateTimeField(blank=True, null=True, db_comment='客户对账日期')
    invoice_date = models.DateTimeField(blank=True, null=True, db_comment='开票日期')
    handlebook_attachment = models.CharField(max_length=255, blank=True, null=True, db_comment='Handlebook附件')
    review_department = models.CharField(max_length=20, blank=True, null=True, db_comment='审核部门')
    reviewer = models.CharField(max_length=20, blank=True, null=True, db_comment='审核人')
    review_time = models.DateTimeField(blank=True, null=True, db_comment='审核时间')
    review_reason = models.CharField(max_length=20, blank=True, null=True, db_comment='审核原因')
    outsourcing_supplier = models.CharField(max_length=20, blank=True, null=True, db_comment='外包供应商')
    upload_result = models.CharField(max_length=255, blank=True, null=True, db_comment='上传结果')
    customer_order_number = models.CharField(max_length=20, blank=True, null=True, db_comment='客户单号')
    closing_time = models.TimeField(blank=True, null=True, db_comment='结案时间')
    customer_requirement = models.CharField(max_length=20, blank=True, null=True, db_comment='客户需求')
    closer = models.CharField(max_length=50, blank=True, null=True, db_comment='结案人')
    commission_to_report_validity = models.CharField(max_length=20, blank=True, null=True, db_comment='委案到报告时效')
    sample_to_report_validity = models.CharField(max_length=20, blank=True, null=True, db_comment='收样到报告时效')
    case_analysis_project_type = models.CharField(max_length=20, blank=True, null=True, db_comment='案例分析项目类型')
    validity_requirement_hours = models.FloatField(blank=True, null=True, db_comment='时效要求(h)')
    customer_bill_status = models.CharField(max_length=20, blank=True, null=True, db_comment='客户账单状态')
    engineer_bill_status = models.CharField(max_length=20, blank=True, null=True, db_comment='工程师账单状态')
    machine_bill_status = models.CharField(max_length=20, blank=True, null=True, db_comment='机台账单状态')
    order_amount = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='订单金额')
    review_date = models.DateTimeField(blank=True, null=True, db_comment='审核日期')
    create_time = models.DateTimeField(db_comment='创建时间')
    modify_time = models.DateTimeField(db_comment='修改时间')
    sender = models.CharField(max_length=20, blank=True, null=True, db_comment='寄件人')
    sender_email = models.CharField(max_length=50, blank=True, null=True, db_comment='寄件人邮箱')
    requirement_confirm_date = models.DateTimeField(blank=True, null=True, db_comment='需求确认日期')
    test_item = models.CharField(max_length=20, blank=True, null=True, db_comment='检测项')
    is_report_required = models.CharField(max_length=10, blank=True, null=True, db_comment='是否需要报告')
    report_format = models.CharField(max_length=20, blank=True, null=True, db_comment='报告形式')
    sample_processing_method = models.CharField(max_length=20, blank=True, null=True, db_comment='样品处理方法')
    execution_place = models.CharField(max_length=20, blank=True, null=True, db_comment='执行地')
    is_order_successful = models.CharField(max_length=10, blank=True, null=True, db_comment='订单是否一次性成功')
    specimen_quantity = models.IntegerField(blank=True, null=True, db_comment='样品数量')

    class Meta:
        managed = False
        db_table = 'order'
