# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Process(models.Model):
    order_id = models.CharField(max_length=30, db_comment='订单编号')
    customer = models.CharField(max_length=30, blank=True, null=True, db_comment='客户')
    test_item = models.CharField(max_length=50, blank=True, null=True, db_comment='检测项目')
    lot_wafer_sample_id = models.CharField(max_length=20, blank=True, null=True, db_comment='Lot/Wafer/Sample ID')
    status = models.CharField(db_column='STATUS', max_length=20, blank=True, null=True, db_comment='状态')  # Field name made lowercase.
    testing_engineer = models.CharField(max_length=20, blank=True, null=True, db_comment='检测工程师')
    testing_machine = models.CharField(max_length=30, blank=True, null=True, db_comment='检测机台')
    machine_model = models.CharField(max_length=50, blank=True, null=True, db_comment='检测机台详细型号')
    machine_code = models.CharField(max_length=30, blank=True, null=True, db_comment='检测机台工序设备编码')
    machine_unit = models.CharField(max_length=20, blank=True, null=True, db_comment='检测机台单位')
    sample_receive_time = models.DateTimeField(blank=True, null=True, db_comment='样点接收时间')
    sample_validity_hours = models.IntegerField(blank=True, null=True, db_comment='样点时效（小时）')
    urgency_level = models.CharField(max_length=20, blank=True, null=True, db_comment='加急程度')
    is_outsource = models.CharField(max_length=10, blank=True, null=True, db_comment='是否委外')
    start_time = models.DateTimeField(blank=True, null=True, db_comment='开始时间')
    end_time = models.DateTimeField(blank=True, null=True, db_comment='结束时间')
    process_category = models.CharField(max_length=20, blank=True, null=True, db_comment='工序类别')
    is_upload_result = models.CharField(max_length=10, blank=True, null=True, db_comment='是否上传结果')
    sample_id = models.CharField(max_length=30, blank=True, null=True, db_comment='检测样点')
    equivalent_point_quantity = models.IntegerField(blank=True, null=True, db_comment='等效点数量')
    execution_plan = models.CharField(max_length=50, blank=True, null=True, db_comment='执行方案')
    associated_machine = models.CharField(max_length=20, blank=True, null=True, db_comment='关联机台（隐藏）')
    priority_level = models.IntegerField(blank=True, null=True, db_comment='优先级')
    time_consumption_minutes = models.IntegerField(blank=True, null=True, db_comment='耗时（分钟）')
    original_test_task = models.CharField(max_length=50, blank=True, null=True, db_comment='原检测任务')
    machine_reconciliation_note = models.CharField(max_length=255, blank=True, null=True, db_comment='机台对账单')
    review_comment = models.CharField(max_length=50, blank=True, null=True, db_comment='审核备注')
    is_canceled = models.CharField(max_length=10, blank=True, null=True, db_comment='是否取消')
    outsourcing_result_file = models.CharField(max_length=255, blank=True, null=True, db_comment='委外结果文件')
    process_id = models.CharField(primary_key=True, max_length=30, db_comment='工序编号')
    customer_sample_id = models.CharField(max_length=30, blank=True, null=True, db_comment='客户样点编号')
    last_process_step = models.CharField(max_length=50, blank=True, null=True, db_comment='最后工艺步骤')
    main_attention_info = models.CharField(max_length=50, blank=True, null=True, db_comment='主要关注信息')
    slice_position = models.CharField(max_length=30, blank=True, null=True, db_comment='切片位置')
    sample_preparation_direction = models.CharField(max_length=30, blank=True, null=True, db_comment='制样方向')
    notes = models.CharField(max_length=50, blank=True, null=True, db_comment='注意事项')
    process_note = models.CharField(max_length=50, blank=True, null=True, db_comment='工序备注')
    supplier_service_item = models.CharField(max_length=50, blank=True, null=True, db_comment='供应商服务项目')
    process_related_result = models.CharField(max_length=50, blank=True, null=True, db_comment='工序相关结果')
    engineer_reconciliation_note = models.CharField(max_length=255, blank=True, null=True, db_comment='工程师对账单')
    engineer_reconciliation_status = models.CharField(max_length=20, blank=True, null=True, db_comment='工程师对账状态')
    associated_machine_reconciliation_detail = models.CharField(max_length=255, blank=True, null=True, db_comment='关联机台对账明细')
    machine_reconciliation_status = models.CharField(max_length=20, blank=True, null=True, db_comment='机台对账状态')
    base_material = models.CharField(max_length=30, blank=True, null=True, db_comment='基底材料')
    e_beam = models.CharField(max_length=30, blank=True, null=True, db_comment='E - beam')
    sample_materials = models.CharField(max_length=50, blank=True, null=True, db_comment='样品所含材质')
    sample_confirmation_date = models.DateTimeField(blank=True, null=True, db_comment='样点确认日期')
    sample_confirmation_time = models.DateTimeField(blank=True, null=True, db_comment='样点确认时间')
    order_date = models.DateTimeField(blank=True, null=True, db_comment='订单日期')
    is_calculate_performance = models.CharField(max_length=10, blank=True, null=True, db_comment='是否计算绩效')
    billing_quantity = models.FloatField(blank=True, null=True, db_comment='计费数量')
    create_time = models.DateTimeField(blank=True, null=True, db_comment='创建时间')
    modify_time = models.DateTimeField(blank=True, null=True, db_comment='修改时间')
    failure_proof = models.CharField(max_length=50, blank=True, null=True, db_comment='失败证明')
    order_category = models.CharField(max_length=20, blank=True, null=True, db_comment='订单类目')
    supplier = models.CharField(max_length=30, blank=True, null=True, db_comment='供应商')
    charge_quantity = models.FloatField(blank=True, null=True, db_comment='收费数量')
    engineer_region = models.CharField(max_length=30, blank=True, null=True, db_comment='工程师区域')
    standard_working_hours_minutes = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='标准工时（分钟）')
    is_rework_process = models.CharField(max_length=10, blank=True, null=True, db_comment='是否为返工工序')
    experience_summary = models.CharField(max_length=50, blank=True, null=True, db_comment='经验总结')
    urgency_coefficient = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='加急系数')
    sample_receive_date = models.DateTimeField(blank=True, null=True, db_comment='样点接收日期')
    associated_customer = models.CharField(max_length=30, blank=True, null=True, db_comment='关联客户')
    associated_transfer_record = models.CharField(max_length=50, blank=True, null=True, db_comment='关联转交记录')
    closing_date = models.DateTimeField(blank=True, null=True, db_comment='结案日期')
    machine_supplier = models.CharField(max_length=30, blank=True, null=True, db_comment='机台供应商')
    scan_to_machine_reminder_minutes = models.CharField(max_length=30, blank=True, null=True, db_comment='分钟内扫码上机提醒')
    test_item_name = models.CharField(max_length=30, blank=True, null=True, db_comment='检测项目名')
    supplier_reconciliation_status = models.CharField(max_length=30, blank=True, null=True, db_comment='供应商对账状态')
    supplier_reconciliation_detail = models.CharField(max_length=50, blank=True, null=True, db_comment='供应商对账单明细')
    supplier_reconciliation_note = models.CharField(max_length=50, blank=True, null=True, db_comment='供应商对账单')
    supplier_charge_quantity = models.FloatField(blank=True, null=True, db_comment='供应商收费数量')
    received_customer_quantity = models.FloatField(blank=True, null=True, db_comment='实收客户数量')
    validity_start_time = models.DateTimeField(blank=True, null=True, db_comment='时效起算时间')
    validity = models.CharField(max_length=20, blank=True, null=True, db_comment='时效')
    process_start_date = models.DateTimeField(blank=True, null=True, db_comment='工序开始日期')
    direct_labor_cost = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='直接人工成本')
    management_labor_cost = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='管理人工成本')
    total_labor_cost = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='总人工成本')
    equipment_maintenance_cost = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='设备维护费')
    equipment_depreciation = models.CharField(max_length=20, blank=True, null=True, db_comment='设备折旧')
    laboratory_equipment_consumables = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='实验室设备易耗品')
    intangible_asset_amortization = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='无形资产摊销')
    office_expense = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='办公费')
    entertainment_expense = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='业务招待费')
    transportation_expense = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='市内交通费')
    car_expense = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='汽车费用')
    travel_expense = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='差旅费')
    rent_and_utility_expense = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='租金水电')
    freight_expense = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='货运费')
    express_expense = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='快递费')
    business_expense = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='商务费用')
    supplier_cost = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='供应商成本')
    sim_salary = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='SIMS 薪酬')
    outsourcing_salary = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='委外薪酬')
    external_aid_cost = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='外援成本')
    total_cost = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='总成本')
    supplier_service_item_quote_untaxed = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='供应商服务项目报价(未税)')
    supplier_service_item_quote_taxed = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='供应商服务项目报价(含税)')
    supplier_cost_again = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='供应商成本')
    customer_full_name1 = models.CharField(max_length=50, blank=True, null=True, db_comment='客户全称1')
    sim_outsourcing_test_cost = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='SIMS委外检测成本')
    performance_working_hours = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='绩效工时')
    note = models.CharField(max_length=50, blank=True, null=True, db_comment='备注')
    working_hours = models.DecimalField(max_digits=20, decimal_places=5, blank=True, null=True, db_comment='工时')
    associated_report_detail = models.CharField(max_length=50, blank=True, null=True, db_comment='关联研发报表明细')
    sender_name = models.CharField(max_length=20, blank=True, null=True, db_comment='送件人名称')
    demo_urgency = models.CharField(max_length=20, blank=True, null=True, db_comment='demo/加急')
    test_item_name_virtual = models.CharField(max_length=50, blank=True, null=True, db_comment='检测项目名(虚拟)')

    class Meta:
        managed = False
        db_table = 'process'
        db_table_comment = '工序列表'
